language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10.5.0'
install:
  - npm i
before_script:
  - chmod ugo+x __tests__/__fixtures__/test-push-server.git/hooks/update
  - chmod ugo+x __tests__/__fixtures__/test-push-server.git/hooks/post-receive
  - ./node_modules/.bin/cors-proxy start -p 9999 &
script:
  - node __tests__/__helpers__/can-i-skip-tests.js .all-contributorsrc CODE_OF_CONDUCT.md CONTRIBUTING.md LICENSE.md README.md renovate.json __tests__/__fixtures__/test-push-server.git/hooks/post-receive || npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  # Only build for PRs and the master branch (https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262)
  only:
    - "master"
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  firefox: latest
